bitexpert_product_document_shop_product_document_download:
    path: /product-documents/{id}/download
    methods: [GET]
    defaults:
        _controller: BitExpert\SyliusProductDocumentPlugin\Controller\ProductDocumentController::downloadAction
