sylius_twig_hooks:
    hooks:
        'sylius_admin.product.create.content.form.side_navigation':
            documents:
                template: '@BitExpertSyliusProductDocumentPlugin/Admin/Product/form/side_navigation/documents.html.twig'
                priority: -100

        'sylius_admin.product.create.content.form.sections':
            documents:
                template: '@BitExpertSyliusProductDocumentPlugin/Admin/Product/form/sections/documents.html.twig'
                priority: -100

        'sylius_admin.product.update.content.form.side_navigation':
            documents:
                template: '@BitExpertSyliusProductDocumentPlugin/Admin/Product/form/side_navigation/documents.html.twig'
                priority: -100

        'sylius_admin.product.update.content.form.sections':
            documents:
                template: '@BitExpertSyliusProductDocumentPlugin/Admin/Product/form/sections/documents.html.twig'
                priority: -100
